//crear usuarios y roles //

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

//1.1 CREACIÓN DE USUARIOS//


CREATE USER PRY2205_EFT
IDENTIFIED BY "EftSeguro2025AA99"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS
PASSWORD EXPIRE;



CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "DesSeguro2025BB88"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS
PASSWORD EXPIRE;

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "ConSeguro2025CC77"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS
PASSWORD EXPIRE;

// PRIVILEGIOS BÁSICOS DE CONEXIÓN//
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

// PRIVILEGIOS ESPECÍFICOS PARA PRY2205_EFT (USUARIO DUEÑO)//

GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE INDEX TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;

------------------------------------------------------------
-- SECCIÓN 2: CREACION DE ROLES (SYS)
--=========================================
DROP ROLE PRY2205_ROL_D;
DROP ROLE PRY2205_ROL_C;

CREATE ROLE PRY2205_ROL_D;  -- Rol para desarrollador
CREATE ROLE PRY2205_ROL_C;  -- Rol para consultor

-- 2.1 PRIVILEGIOS PARA ROLES
GRANT CREATE SESSION, CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SESSION TO PRY2205_ROL_C;

-- 2.2 ASIGNACIÓN DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;



BEGIN
    -- Eliminar usuarios si existen
    FOR u IN (SELECT username FROM dba_users WHERE username LIKE 'PRY2205_%') LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || u.username || ' CASCADE';
        DBMS_OUTPUT.PUT_LINE('Usuario eliminado: ' || u.username);
    END LOOP;
    
    -- Eliminar roles si existen
    FOR r IN (SELECT role FROM dba_roles WHERE role LIKE 'PRY2205_%') LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || r.role;
        DBMS_OUTPUT.PUT_LINE('Rol eliminado: ' || r.role);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('? Limpieza completada');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('?? Limpieza: ' || SQLERRM);
END;


// SECCIÓN 1: CREACIÓN DE USUARIOS//

//USUARIO DUEÑO /OWNER//

CREATE USER PRY2205_EFT
IDENTIFIED BY "EftSeguro2025AA99"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;


//USUARIO GENERICO/ DESARROLLADOR//

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "DesSeguro2025BB88"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;



//USUARIO GENERICO / CONSTRUCTOR//

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "ConSeguro2025CC77"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;


// PRIVILEGIOS BÁSICOS DE CONEXIÓN//
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

// PRIVILEGIOS ESPECÍFICOS PARA PRY2205_EFT (USUARIO DUEÑO)//

GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE INDEX TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;

//PRIVILEGIOS PARA SINONIMOS, Otorgar CREATE SYNONYM a PRY2205_EFT_DES//

GRANT CREATE SYNONYM TO PRY2205_EFT_DES;

------------------------------------------------------------
-- SECCIÓN 2: CREACION DE ROLES (SYS)
--=========================================
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_D';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_C';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

CREATE ROLE PRY2205_ROL_D;  -- Rol para desarrollador
CREATE ROLE PRY2205_ROL_C;  -- Rol para consultor

-- 2.1 PRIVILEGIOS PARA ROLES
GRANT CREATE SESSION, CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SESSION TO PRY2205_ROL_C;

-- 2.2 ASIGNACIÓN DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

GRANT GRANT ANY OBJECT PRIVILEGE TO PRY2205_EFT_DES;










