------------------------------------------------------------
-- SECCIÓN 1: USUARIO ADMIN (SYS)
--=========================================
-- Conectarse como SYS 
------------------------------------------------------------
// SECCIÓN 1: CREACIÓN DE USUARIOS//

//USUARIO DUEÑO /OWNER//

CREATE USER PRY2205_EFT
IDENTIFIED BY "EftSeguro2025AA99"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;


//USUARIO GENERICO/ DESARROLLADOR//

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "DesSeguro2025BB88"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;



//USUARIO GENERICO / CONSTRUCTOR//

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "ConSeguro2025CC77"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;


// PRIVILEGIOS BÁSICOS DE CONEXIÓN//
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

// PRIVILEGIOS ESPECÍFICOS PARA PRY2205_EFT (USUARIO DUEÑO)//

GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE INDEX TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;

//PRIVILEGIOS PARA SINONIMOS, Otorgar CREATE SYNONYM a PRY2205_EFT_DES//

GRANT CREATE SYNONYM TO PRY2205_EFT_DES;


------------------------------------------------------------
-- SECCIÓN 2: CREACION DE ROLES (SYS)
--=========================================

CREATE ROLE PRY2205_ROL_D;  -- Rol para desarrollador
CREATE ROLE PRY2205_ROL_C;  -- Rol para consultor

-- 2.1 PRIVILEGIOS PARA ROLES
GRANT CREATE SESSION, CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SESSION TO PRY2205_ROL_C;

-- 2.2 ASIGNACIÓN DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;



------------------------------------------------------------
-- SECCION 3 :PRY2205_EFT crea tablas y sinónimos
--  USUARIO DUEÑO -PRY2205_EFT
--=========================================
-- Conectarse como PRY2205_EFT
------------------------------------------------------------
-- Una vez conectado como PRY2205_EFT, ejecutar:
--1. SCRIPT TABLAS
-- el script de tablas:
-- se va a ejecutar en la sesión de PRY2205_EFT

-- 2. VERIFICAR que las tablas se crearon:
SELECT table_name FROM user_tables ORDER BY table_name;
-- Deberías ver tablas como: PROFESIONAL, EMPRESA, ASESORIA, CARTOLA_PROFESIONALES, etc.

-- 3. CREAR SINÓNIMOS PÚBLICOS:
CREATE PUBLIC SYNONYM SIN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM SIN_EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM SIN_ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE PUBLIC SYNONYM SIN_CARTOLA FOR PRY2205_EFT.CARTOLA_PROFESIONALES;
CREATE PUBLIC SYNONYM SIN_PROFESION FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM SIN_ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM SIN_TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM SIN_RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;

-- 4. VERIFICAR sinónimos creados:
SELECT synonym_name, table_name FROM user_synonyms WHERE table_owner = 'PRY2205_EFT';

-- 5. OTORGAR SELECT A LOS ROLES:
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.EMPRESA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ASESORIA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_D;

GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;

-- 6. VERIFICAR privilegios otorgados,quien recibe esos privilegios
SELECT grantee, table_name, privilege 
FROM user_tab_privs 
WHERE grantee IN ('PRY2205_ROL_D', 'PRY2205_ROL_C')
ORDER BY grantee, table_name;

-- 7. Conéctarse como PRY2205_EFT y ejecutar permisos:
GRANT INSERT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_D;
GRANT INSERT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;


-- ============================================
-- SECCION 4: PRY2205_EFT_DES CREA SINÓNIMOS PRIVADOS
-- Conectarse como PRY2205_EFT_DES 
-- ============================================
//verificaR que se acceder a los sinónimos públicos//

DESC SIN_PROFESIONAL;  -- Debería mostrar la estructura
SELECT COUNT(*) FROM SIN_PROFESIONAL;  -- va a mostrar el número de registros de la tabla profesional

SELECT * FROM PROFESIONAL;  -- Sinónimo público
SELECT * FROM SIN_PROFESIONAL;  -- Sinónimo privado



-- Crear sinónimos privados
CREATE SYNONYM PROFESIONAL FOR SIN_PROFESIONAL;
CREATE SYNONYM EMPRESA FOR SIN_EMPRESA;
CREATE SYNONYM ASESORIA FOR SIN_ASESORIA;
CREATE SYNONYM CARTOLA FOR SIN_CARTOLA;
CREATE SYNONYM PROFESION FOR SIN_PROFESION;
CREATE SYNONYM ISAPRE FOR SIN_ISAPRE;
CREATE SYNONYM TIPO_CONTRATO FOR SIN_TIPO_CONTRATO;
CREATE SYNONYM RANGOS_SUELDOS FOR SIN_RANGOS_SUELDOS;

-- Verificar sinónimos privados:
SELECT synonym_name, table_name FROM user_synonyms;

-- Probar consulta con sinónimos privados
SELECT COUNT(*) FROM PROFESIONAL;      -- Va a mostrar número de profesionales de la tabla
SELECT COUNT(*) FROM ASESORIA;         -- va mostrar número de asesorías de la tabla


-- En PRY2205_EFT_DES, vamos a  verificar los acceso a los sinónimos públicos

SELECT * FROM ALL_SYNONYMS 
WHERE OWNER = 'PUBLIC' 
AND SYNONYM_NAME IN (
    'SIN_PROFESIONAL', 'SIN_EMPRESA', 'SIN_ASESORIA', 'SIN_CARTOLA',
    'SIN_PROFESION', 'SIN_ISAPRE', 'SIN_TIPO_CONTRATO', 'SIN_RANGOS_SUELDOS'
);

-- ============================================
-- CASO 2: INFORME DE REMUNERACIONES
-- Conéctarse como PRY2205_EFT_DES
-- ============================================


-- Usuario PRY2205_EFT_DES ejecuta esta consulta para generar y almacenar el informe

--Muestra la estructura de la tabla CARTOLA--

   
DESC CARTOLA;

INSERT INTO CARTOLA
SELECT 
    P.RUTPROF AS RUT_PROFESIONAL,
    SUBSTR(P.NOMPRO || ' ' || P.APPPRO || ' ' || P.APMPRO, 1, 50) AS NOMBRE_PROFESIONAL,
    SUBSTR(PR.NOMPROFESION, 1, 25) AS PROFESION,
    SUBSTR(I.NOMISAPRE, 1, 25) AS ISAPRE,
    LEAST(P.SUELDO, 99999999) AS SUELDO_BASE,  -- Limita a 8 dígitos
    NVL(P.COMISION, 0) AS PORC_COMISION_PROFESIONAL,
    LEAST(NVL(P.SUELDO * NVL(P.COMISION, 0), 0), 99999999) AS VALOR_TOTAL_COMISION,
    CASE
        WHEN P.SUELDO BETWEEN RS.S_MIN AND RS.S_MAX THEN LEAST(RS.HONOR_PCT, 99999999)
        ELSE 0
    END AS PORCENTATE_HONORARIO,
    CASE TC.NOMTCONTRATO
        WHEN 'Indefinido Jornada Completa' THEN 150000
        WHEN 'Indefinido Jornada Parcial' THEN 120000
        WHEN 'Plazo fijo' THEN 60000
        WHEN 'Honorarios' THEN 50000
        ELSE 0
    END AS BONO_MOVILIZACION,
    LEAST(
        P.SUELDO + 
        NVL(P.SUELDO * NVL(P.COMISION, 0), 0) + 
        CASE
            WHEN P.SUELDO BETWEEN RS.S_MIN AND RS.S_MAX THEN (P.SUELDO * RS.HONOR_PCT / 100)
            ELSE 0
        END +
        CASE TC.NOMTCONTRATO
            WHEN 'Indefinido Jornada Completa' THEN 150000
            WHEN 'Indefinido Jornada Parcial' THEN 120000
            WHEN 'Plazo fijo' THEN 60000
            WHEN 'Honorarios' THEN 50000
            ELSE 0
        END,
        99999999
    ) AS TOTAL_PAGAR
FROM PROFESIONAL P
INNER JOIN PROFESION PR ON P.IDPROFESION = PR.IDPROFESION
INNER JOIN ISAPRE I ON P.IDISAPRE = I.IDISAPRE
INNER JOIN TIPO_CONTRATO TC ON P.IDTCONTRATO = TC.IDTCONTRATO
LEFT JOIN RANGOS_SUELDOS RS ON P.SUELDO BETWEEN RS.S_MIN AND RS.S_MAX
ORDER BY 
    PR.NOMPROFESION,
    P.SUELDO DESC,
    NVL(P.COMISION, 0),
    P.RUTPROF;


-- Verificar que se insertaron todas las filas
SELECT COUNT(*) FROM CARTOLA;

-- Ver todos los datos 
SELECT * FROM CARTOLA ORDER BY RUT_PROFESIONAL;

--•	El usuario PRY2205_EFT_DES da permiso al usuario PRY2205_EFT_CON sobre la tabla CARTOLA, para que pueda ver los datos 
GRANT SELECT ON CARTOLA TO PRY2205_EFT_CON;


--El usuario  PRY2205_EFT_CON va revisar si tiene acceso 
--  ejecuta: Las primeras 5 filas con todas las columnas

SELECT COUNT(*) FROM PRY2205_EFT_DES.CARTOLA;
SELECT * FROM PRY2205_EFT_DES.CARTOLA WHERE ROWNUM <= 5;



-- ============================================
-- CASO 3: INFORME DE REMUNERACIONES
-- Conéctarse como PRY2205_EFT_DES
-- ============================================
// CASO 3 //

-- Conectado en este usuario PRY2205_EFT, VAMOS A CREAR View VW_EMPRESAS_ASESORADAS creado

CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    -- RUT formateado con punto y guión (formato chileno: 99.999.999-X)
    TO_CHAR(E.RUT_EMPRESA, 'FM99G999G999') || '-' || E.DV_EMPRESA AS "RUT EMPRESA",
    
    -- Nombre empresa en MAYÚSCULAS
    UPPER(E.NOMEMPRESA) AS "NOMBRE EMPRESA",
    
    -- Años de antigüedad (año actual - año inicio)
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM E.FECHA_INICIACION_ACTIVIDADES) AS "AÑOS ANTIGÜEDAD",
    
    -- IVA declarado con formato
    TO_CHAR(E.IVA_DECLARADO, 'FM999G999G999') AS "IVA DECLARADO",
    
    -- Total de asesorías el año anterior
    COUNT(A.IDEMPRESA) AS "TOTAL ASESORÍAS",
    
    -- Promedio mensual de asesorías (total/12, 2 decimales)
    ROUND(COUNT(A.IDEMPRESA) / 12, 2) AS "PROMEDIO MENSUAL ASESORÍAS",
    
    -- Monto estimado devolución IVA: IVA * (promedio_mensual/100)
    TO_CHAR(
        ROUND(E.IVA_DECLARADO * (COUNT(A.IDEMPRESA) / 12 / 100), 0),
        'FM999G999G999'
    ) AS "MONTO ESTIMADO DEVOLUCIÓN IVA",
    
    -- Tipo de cliente según TOTAL asesorías anuales
    CASE 
        WHEN COUNT(A.IDEMPRESA) > 5 THEN 'CLIENTE PREMIUM'
        WHEN COUNT(A.IDEMPRESA) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS "TIPO CLIENTE",
    
    -- Promoción/Recomendación basada en TOTAL asesorías
    CASE 
        -- CLIENTE PREMIUM (> 5 asesorías)
        WHEN COUNT(A.IDEMPRESA) > 5 THEN
            CASE 
                WHEN COUNT(A.IDEMPRESA) >= 7 THEN '1 ASESORÍA GRATIS'
                ELSE '1 ASESORÍA 40% DE DESCUENTO'
            END
        -- CLIENTE (3-5 asesorías)
        WHEN COUNT(A.IDEMPRESA) BETWEEN 3 AND 5 THEN
            CASE 
                WHEN COUNT(A.IDEMPRESA) = 5 THEN '1 ASESORÍA 30% DE DESCUENTO'
                ELSE '1 ASESORÍA 20% DE DESCUENTO'
            END
        -- CLIENTE POCO CONCURRIDO (< 3 asesorías)
        ELSE 'CAPTAR CLIENTE'
    END AS "PROMOCIÓN/RECOMENDACIÓN"

FROM SIN_EMPRESA E
LEFT JOIN SIN_ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    -- Solo asesorías terminadas el año anterior al actual
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
    -- Solo asesorías con fecha FIN válida
    AND A.FIN IS NOT NULL

-- Agrupar por empresa
GROUP BY 
    E.RUT_EMPRESA, 
    E.DV_EMPRESA,
    E.NOMEMPRESA,
    E.FECHA_INICIACION_ACTIVIDADES,
    E.IVA_DECLARADO

-- Solo incluir empresas que tuvieron asesorías
HAVING COUNT(A.IDEMPRESA) > 0

-- Ordenar por nombre de empresa ascendente
ORDER BY E.NOMEMPRESA ASC;

-- Probar la vista, Ver cuántas filas tiene
SELECT COUNT(*) AS "TOTAL EMPRESAS" FROM VW_EMPRESAS_ASESORADAS;


-- Ver las primeras filas
SELECT * FROM VW_EMPRESAS_ASESORADAS WHERE ROWNUM <= 5;


-- Verificar que la vista se creó
SELECT VIEW_NAME, TEXT_LENGTH 
FROM USER_VIEWS 
WHERE VIEW_NAME = 'VW_EMPRESAS_ASESORADAS';

-- Dar permiso SELECT
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;

-- Verificar permisos otorgados
SELECT GRANTEE, PRIVILEGE, GRANTABLE, TYPE
FROM USER_TAB_PRIVS 
WHERE TABLE_NAME = 'VW_EMPRESAS_ASESORADAS';


-- PRY2205_EFT_CON se conecta y ejecuta:

-- Usando nombre completo
SELECT COUNT(*) FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

-- Ver datos, que nos muestre 3 datos
SELECT * FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS WHERE ROWNUM <= 3;


// CASO 3.2 //
--Para crear índices (Caso 3.2):

-- Como PRY2205_EFT, vamos a crear índices para optimizar
-- Índice en ASESORIA para búsqueda por año
CREATE INDEX IDX_ASESORIA_FIN_ANIO ON ASESORIA(EXTRACT(YEAR FROM FIN));

-- Índice en EMPRESA para ordenamiento
CREATE INDEX IDX_EMPRESA_NOMBRE ON EMPRESA(NOMEMPRESA);

-- Índice compuesto para JOIN
CREATE INDEX IDX_ASESORIA_EMPRESA_ID ON ASESORIA(IDEMPRESA, FIN);

-- Ver índices creados
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE TABLE_NAME IN ('ASESORIA', 'EMPRESA');


--Solo ver el plan de ejecución
EXPLAIN PLAN FOR
SELECT * FROM VW_EMPRESAS_ASESORADAS WHERE ROWNUM <= 10;

-- Mostrar el plan
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Evidencia de índices creados
SELECT * FROM USER_INDEXES 
WHERE TABLE_NAME IN ('ASESORIA', 'EMPRESA');

-- COMPARACIÓN DE PLANES DE EJECUCIÓN
-- 1. Plan SIN usar índices (forzando FULL TABLE SCAN)
EXPLAIN PLAN SET STATEMENT_ID = 'SIN_INDICES' FOR
SELECT /*+ FULL(E) FULL(A) NO_INDEX(E) NO_INDEX(A) */ 
    E.NOMEMPRESA,
    COUNT(A.IDEMPRESA) AS TOTAL_ASESORIAS
FROM EMPRESA E
LEFT JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY E.NOMEMPRESA;

-- 2. Plan CON índices (dejando que el optimizador decida)
EXPLAIN PLAN SET STATEMENT_ID = 'CON_INDICES' FOR
SELECT 
    E.NOMEMPRESA,
    COUNT(A.IDEMPRESA) AS TOTAL_ASESORIAS
FROM EMPRESA E
LEFT JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY E.NOMEMPRESA;

SELECT 
    '=== PLAN SIN ÍNDICES ===' AS PLAN
FROM DUAL
UNION ALL
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'SIN_INDICES', 'TYPICAL'))
UNION ALL
SELECT ' ' FROM DUAL
UNION ALL
SELECT '=== PLAN CON ÍNDICES ===' 
FROM DUAL
UNION ALL
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'CON_INDICES', 'TYPICAL'));

---"Los índices funcionan, Oracle los usa, y aunque el número no cambie, 
--- la forma de acceder a los datos es más eficiente."




















