SELECT table_name FROM user_tables ORDER BY table_name;

-- 3. CREAR SINÓNIMOS PÚBLICOS:
CREATE PUBLIC SYNONYM SIN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM SIN_EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM SIN_ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE PUBLIC SYNONYM SIN_CARTOLA FOR PRY2205_EFT.CARTOLA_PROFESIONALES;
CREATE PUBLIC SYNONYM SIN_PROFESION FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM SIN_ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM SIN_TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM SIN_RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;

-- 4. VERIFICAR sinónimos creados:
SELECT synonym_name, table_name FROM user_synonyms WHERE table_owner = 'PRY2205_EFT';

-- 5. OTORGAR SELECT A LOS ROLES:
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.EMPRESA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ASESORIA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_D;

GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;

-- 6. VERIFICAR privilegios otorgados, quien recibe esos privilegios
SELECT grantee, table_name, privilege 
FROM user_tab_privs 
WHERE grantee IN ('PRY2205_ROL_D', 'PRY2205_ROL_C')
ORDER BY grantee, table_name;

-- como PRY2205_EFT ejecutar permisos:
GRANT INSERT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_D;
GRANT INSERT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;


-- Conectado en este usuario PRY2205_EFT

CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    -- RUT formateado con punto y guión (formato chileno: 99.999.999-X)
    TO_CHAR(E.RUT_EMPRESA, 'FM99G999G999') || '-' || E.DV_EMPRESA AS "RUT EMPRESA",
    
    -- Nombre empresa en MAYÚSCULAS
    UPPER(E.NOMEMPRESA) AS "NOMBRE EMPRESA",
    
    -- Años de antigüedad (año actual - año inicio)
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM E.FECHA_INICIACION_ACTIVIDADES) AS "AÑOS ANTIGÜEDAD",
    
    -- IVA declarado con formato
    TO_CHAR(E.IVA_DECLARADO, 'FM999G999G999') AS "IVA DECLARADO",
    
    -- Total de asesorías el año anterior
    COUNT(A.IDEMPRESA) AS "TOTAL ASESORÍAS",
    
    -- Promedio mensual de asesorías (total/12, 2 decimales)
    ROUND(COUNT(A.IDEMPRESA) / 12, 2) AS "PROMEDIO MENSUAL ASESORÍAS",
    
    -- Monto estimado devolución IVA: IVA * (promedio_mensual/100)
    TO_CHAR(
        ROUND(E.IVA_DECLARADO * (COUNT(A.IDEMPRESA) / 12 / 100), 0),
        'FM999G999G999'
    ) AS "MONTO ESTIMADO DEVOLUCIÓN IVA",
    
    -- Tipo de cliente según TOTAL asesorías anuales
    CASE 
        WHEN COUNT(A.IDEMPRESA) > 5 THEN 'CLIENTE PREMIUM'
        WHEN COUNT(A.IDEMPRESA) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS "TIPO CLIENTE",
    
    -- Promoción/Recomendación basada en TOTAL asesorías
    CASE 
        -- CLIENTE PREMIUM (> 5 asesorías)
        WHEN COUNT(A.IDEMPRESA) > 5 THEN
            CASE 
                WHEN COUNT(A.IDEMPRESA) >= 7 THEN '1 ASESORÍA GRATIS'
                ELSE '1 ASESORÍA 40% DE DESCUENTO'
            END
        -- CLIENTE (3-5 asesorías)
        WHEN COUNT(A.IDEMPRESA) BETWEEN 3 AND 5 THEN
            CASE 
                WHEN COUNT(A.IDEMPRESA) = 5 THEN '1 ASESORÍA 30% DE DESCUENTO'
                ELSE '1 ASESORÍA 20% DE DESCUENTO'
            END
        -- CLIENTE POCO CONCURRIDO (< 3 asesorías)
        ELSE 'CAPTAR CLIENTE'
    END AS "PROMOCIÓN/RECOMENDACIÓN"

FROM SIN_EMPRESA E
LEFT JOIN SIN_ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    -- Solo asesorías terminadas el año anterior al actual
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
    -- Solo asesorías con fecha FIN válida
    AND A.FIN IS NOT NULL

-- Agrupar por empresa
GROUP BY 
    E.RUT_EMPRESA, 
    E.DV_EMPRESA,
    E.NOMEMPRESA,
    E.FECHA_INICIACION_ACTIVIDADES,
    E.IVA_DECLARADO

-- Solo incluir empresas que tuvieron asesorías
HAVING COUNT(A.IDEMPRESA) > 0

-- Ordenar por nombre de empresa ascendente
ORDER BY E.NOMEMPRESA ASC;


-- Probar la vista, Ver cuántas filas tiene
SELECT COUNT(*) AS "TOTAL EMPRESAS" FROM VW_EMPRESAS_ASESORADAS;

-- Ver las primeras filas
SELECT * FROM VW_EMPRESAS_ASESORADAS WHERE ROWNUM <= 5;

-- Verificar que la vista se creó
SELECT VIEW_NAME, TEXT_LENGTH 
FROM USER_VIEWS 
WHERE VIEW_NAME = 'VW_EMPRESAS_ASESORADAS';

-- Dar permiso SELECT
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;


--  Verificar permisos otorgados
SELECT GRANTEE, PRIVILEGE, GRANTABLE, TYPE
FROM USER_TAB_PRIVS 
WHERE TABLE_NAME = 'VW_EMPRESAS_ASESORADAS';


// CASO 3.2 //
--Para crear índices (Caso 3.2):

-- Como PRY2205_EFT, vamos a crear índices para optimizar
-- Índice en ASESORIA para búsqueda por año
CREATE INDEX IDX_ASESORIA_FIN_ANIO ON ASESORIA(EXTRACT(YEAR FROM FIN));

-- Índice en EMPRESA para ordenamiento
CREATE INDEX IDX_EMPRESA_NOMBRE ON EMPRESA(NOMEMPRESA);

-- Índice compuesto para JOIN
CREATE INDEX IDX_ASESORIA_EMPRESA_ID ON ASESORIA(IDEMPRESA, FIN);

-- Ver índices creados
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE TABLE_NAME IN ('ASESORIA', 'EMPRESA');


--Solo ver el plan de ejecución
EXPLAIN PLAN FOR
SELECT * FROM VW_EMPRESAS_ASESORADAS WHERE ROWNUM <= 10;

-- Mostrar el plan
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Evidencia de índices creados
SELECT * FROM USER_INDEXES 
WHERE TABLE_NAME IN ('ASESORIA', 'EMPRESA');


-- COMPARACIÓN DE PLANES DE EJECUCIÓN
-- 1. Plan SIN usar índices (forzando FULL TABLE SCAN)
EXPLAIN PLAN SET STATEMENT_ID = 'SIN_INDICES' FOR
SELECT /*+ FULL(E) FULL(A) NO_INDEX(E) NO_INDEX(A) */ 
    E.NOMEMPRESA,
    COUNT(A.IDEMPRESA) AS TOTAL_ASESORIAS
FROM EMPRESA E
LEFT JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY E.NOMEMPRESA;

-- 2. Plan CON índices (dejando que el optimizador decida)
EXPLAIN PLAN SET STATEMENT_ID = 'CON_INDICES' FOR
SELECT 
    E.NOMEMPRESA,
    COUNT(A.IDEMPRESA) AS TOTAL_ASESORIAS
FROM EMPRESA E
LEFT JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
    AND EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY E.NOMEMPRESA;

SELECT 
    '=== PLAN SIN ÍNDICES ===' AS PLAN
FROM DUAL
UNION ALL
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'SIN_INDICES', 'TYPICAL'))
UNION ALL
SELECT ' ' FROM DUAL
UNION ALL
SELECT '=== PLAN CON ÍNDICES ===' 
FROM DUAL
UNION ALL
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'CON_INDICES', 'TYPICAL'));

---"Los índices funcionan, Oracle los usa, y aunque el número no cambie, 
--- la forma de acceder a los datos es más eficiente."






