//CASO 1//
SELECT * FROM profesional;
--ID_PROFESIONAL
--APPATERNO
--APMATERNO
--NOMBRE
SELECT * FROM asesoria;
--ID_PROFESIONAL
--COD_EMPRESA
--HONORARIO
--FIN_ASESORIA
SELECT * FROM empresa; 
--COD_EMPRESA
--COD SECTOR, 3 BANCA , 4 RETAIL

SELECT 
    ID_PROFESIONAL AS "Id Profesional",
    NOMBRE_COMPLETO AS "Nombre Completo",
    CANTIDAD_BANCA AS "N° Asesorías Banca",
    MONTO_BANCA AS "Monto Total Banca",
    CANTIDAD_RETAIL AS "N° Asesorías Retail", 
    MONTO_RETAIL AS "Monto Total Retail",
    (CANTIDAD_BANCA + CANTIDAD_RETAIL) AS "Total Asesorías",
    (MONTO_BANCA + MONTO_RETAIL) AS "Total Honorarios"
FROM (
    SELECT 
        P.ID_PROFESIONAL,
        INITCAP(P.APPATERNO || ' ' || P.APMATERNO || ' ' || P.NOMBRE) AS NOMBRE_COMPLETO,
        NVL((SELECT COUNT(*) 
             FROM ASESORIA A 
             INNER JOIN EMPRESA E ON A.COD_EMPRESA = E.COD_EMPRESA
             WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL 
             AND E.COD_SECTOR = 3
        ), 0) AS CANTIDAD_BANCA,
        
        NVL((SELECT SUM(A.HONORARIO)
             FROM ASESORIA A 
             INNER JOIN EMPRESA E ON A.COD_EMPRESA = E.COD_EMPRESA
             WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL 
             AND E.COD_SECTOR = 3
        ), 0) AS MONTO_BANCA,
        
        NVL((SELECT COUNT(*) 
             FROM ASESORIA A 
             INNER JOIN EMPRESA E ON A.COD_EMPRESA = E.COD_EMPRESA
             WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL 
             AND E.COD_SECTOR = 4
        ), 0) AS CANTIDAD_RETAIL,
        
        NVL((SELECT SUM(A.HONORARIO)
             FROM ASESORIA A 
             INNER JOIN EMPRESA E ON A.COD_EMPRESA = E.COD_EMPRESA
             WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL 
             AND E.COD_SECTOR = 4
        ), 0) AS MONTO_RETAIL
        
    FROM PROFESIONAL P
    WHERE P.ID_PROFESIONAL IN (
        SELECT A1.ID_PROFESIONAL
        FROM ASESORIA A1
        INNER JOIN EMPRESA E1 ON A1.COD_EMPRESA = E1.COD_EMPRESA
        WHERE E1.COD_SECTOR = 3
        
        INTERSECT
        
        SELECT A2.ID_PROFESIONAL
        FROM ASESORIA A2
        INNER JOIN EMPRESA E2 ON A2.COD_EMPRESA = E2.COD_EMPRESA
        WHERE E2.COD_SECTOR = 4
    )
)
WHERE CANTIDAD_BANCA > 0 AND CANTIDAD_RETAIL > 0
ORDER BY "Id Profesional" ASC



//CASO 2//

SELECT * FROM comuna;
--COD_COMUNA
--NOM_COMUNA


--crear tabla

CREATE TABLE REPORTE_MES (
    id_profesional NUMBER(10),
    nombre_completo VARCHAR2(60),
    nombre_profesion VARCHAR2(25),
    nombre_comuna VARCHAR2(20),
    nro_asesorias NUMBER(3),
    monto_total_honorarios NUMBER(10),
    promedio_honorarios NUMBER(10),
    honorario_minimo NUMBER(10),
    honorario_maximo NUMBER(10)
);

INSERT INTO REPORTE_MES (
    id_profesional,
    nombre_completo,
    nombre_profesion,
    nombre_comuna,
    nro_asesorias,
    monto_total_honorarios,
    promedio_honorarios,
    honorario_minimo,
    honorario_maximo
)
SELECT 
    P.ID_PROFESIONAL,
    UPPER(SUBSTR(P.APPATERNO, 1, 1)) || LOWER(SUBSTR(P.APPATERNO, 2)) || ' ' ||
    UPPER(SUBSTR(P.APMATERNO, 1, 1)) || LOWER(SUBSTR(P.APMATERNO, 2)) || ' ' ||
    UPPER(SUBSTR(P.NOMBRE, 1, 1)) || LOWER(SUBSTR(P.NOMBRE, 2)) AS nombre_completo,
    NVL(PR.NOMBRE_PROFESION, 'SIN PROFESION') AS nombre_profesion,
    NVL(C.NOM_COMUNA, 'SIN COMUNA') AS nombre_comuna,
    COUNT(A.ID_PROFESIONAL) AS nro_asesorias,
    ROUND(NVL(SUM(A.HONORARIO), 0)) AS monto_total_honorarios,
    ROUND(NVL(AVG(A.HONORARIO), 0)) AS promedio_honorarios,
    ROUND(NVL(MIN(A.HONORARIO), 0)) AS honorario_minimo,
    ROUND(NVL(MAX(A.HONORARIO), 0)) AS honorario_maximo
FROM PROFESIONAL P
INNER JOIN ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
INNER JOIN PROFESION PR ON P.COD_PROFESION = PR.COD_PROFESION
INNER JOIN COMUNA C ON P.COD_COMUNA = C.COD_COMUNA
WHERE EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
  AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 4
GROUP BY 
    P.ID_PROFESIONAL,
    P.APPATERNO,
    P.APMATERNO,
    P.NOMBRE,
    PR.NOMBRE_PROFESION,
    C.NOM_COMUNA
ORDER BY P.ID_PROFESIONAL ASC;

SELECT * FROM REPORTE_MES ORDER BY id_profesional ASC;



//CASO 3//

---reporte antes de la ctualizacion

SELECT 
    ROUND(SUM(A.HONORARIO)) AS HONORARIO,
    P.ID_PROFESIONAL,
    P.NUMRUN_PROF,
    P.SUELDO
FROM PROFESIONAL P
INNER JOIN ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
WHERE EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
  AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3
GROUP BY P.ID_PROFESIONAL, P.NUMRUN_PROF, P.SUELDO
ORDER BY P.ID_PROFESIONAL ASC;

--actualizacion

UPDATE PROFESIONAL 
SET SUELDO = CASE 
    WHEN (SELECT ROUND(SUM(A.HONORARIO)) 
          FROM ASESORIA A 
          WHERE A.ID_PROFESIONAL = PROFESIONAL.ID_PROFESIONAL
          AND EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
          AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3) < 1000000 
    THEN ROUND(SUELDO * 1.10)  -- 10% de incremento
    
    WHEN (SELECT ROUND(SUM(A.HONORARIO)) 
          FROM ASESORIA A 
          WHERE A.ID_PROFESIONAL = PROFESIONAL.ID_PROFESIONAL
          AND EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
          AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3) >= 1000000 
    THEN ROUND(SUELDO * 1.15)  -- 15% de incremento
    
    ELSE SUELDO  -- Mantiene sueldo si no cumple condiciones
END
WHERE ID_PROFESIONAL IN (
    SELECT DISTINCT P.ID_PROFESIONAL
    FROM PROFESIONAL P
    INNER JOIN ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
    WHERE EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
      AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3
);

---reporte despues de la actualizacion

SELECT 
    ROUND(SUM(A.HONORARIO)) AS HONORARIO,
    P.ID_PROFESIONAL,
    P.NUMRUN_PROF,
    P.SUELDO
FROM PROFESIONAL P
INNER JOIN ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
WHERE EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -12))
  AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3
GROUP BY P.ID_PROFESIONAL, P.NUMRUN_PROF, P.SUELDO
ORDER BY P.ID_PROFESIONAL ASC;
